# Generated by Django 4.1.7 on 2023-09-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_author_joined_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
