# Generated by Django 4.1.7 on 2023-03-29 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='votes',
        ),
    ]
